<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE796XwN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE796XwN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE796XwN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE796XwN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE796XwN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E796XwN',
    'container.build_id' => '39536ee2',
    'container.build_time' => 1634157400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE796XwN');
