<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLNddaAB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLNddaAB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLNddaAB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLNddaAB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLNddaAB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LNddaAB',
    'container.build_id' => 'fc2b85e9',
    'container.build_time' => 1633874991,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLNddaAB');
