<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWGGp9OC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWGGp9OC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWGGp9OC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWGGp9OC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWGGp9OC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WGGp9OC',
    'container.build_id' => '4769d40c',
    'container.build_time' => 1633793744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWGGp9OC');
